name: carp_context_package
description: CARP context sampling package. Samples location, mobility, activity, weather, air-quality, and geofence.
version: 1.3.3
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_context_package

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  carp_serializable: ^1.1.0
  carp_core: ^1.3.0
  carp_mobile_sensing: ^1.3.0
 
  json_annotation: ^4.8.0
  permission_handler: ^11.0.0  
  weather: ^3.1.0
  air_quality: ^4.0.0
  flutter_activity_recognition: ^3.0.0
  openmhealth_schemas: ^0.2.1
  mobility_features: ^4.0.0
  location: ^5.0.0  
  # carp_background_location: ^4.0.0 # the CARP location plugin

# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
  # openmhealth_schemas:
  #   path: ../../../openmhealth_schemas/
  # mobility_features:
  #   path: ../../../../flutter-plugins/packages/mobility_features/


dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

