name: carp_webservices_example
description: An small example of how to usee the CARP web service package.
version: 0.0.1
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_core

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carp_mobile_sensing:
    path: ../../../carp_mobile_sensing
  carp_webservices:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
