name: carp_firebase_backend_example
description: Examples of how to use the plugin to upload data to Google Firebase.
version: 0.0.1
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_firebase_backend

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.0.0
  google_sign_in: ^3.0.5
  firebase_storage: ^1.0.2
  firebase_auth: ^0.5.20
  carp_core: ^0.1.0                   # The core CARP domain model
  carp_mobile_sensing: ^0.2.4
  carp_firebase_backend:


# Overriding carp_firebase_backend to use the local copy
# Remove this when done development
#dependency_overrides:
#  carp_firebase_backend:
#    path: ../carp_firebase_backend/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:       # used to build JSON serialization .g files
  json_serializable: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

