name: carp_movisens_package
description: CARP Movisens sampling package. Samples movement, activity, HRV, MET-level, and ECG for the Movisens Move4 and EcgMove4 devices
version: 0.40.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_movisens_package

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_core: ^0.40.0
  # carp_mobile_sensing: ^0.40.0
 
  json_annotation: ^4.4.0
  permission_handler: ^10.0.0  
  movisens_flutter: ^0.2.0
  convert: ^3.0.1
  openmhealth_schemas: ^0.2.1+1


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  #movisens_flutter:
   # git:
   #   url: git://github.com/cph-cachet/flutter-plugins.git
   #   path: packages/movisens_flutter


dev_dependencies:
  lints: any
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:

