name: carp_movisens_package
description: CARP Movisens sampling package. Samples movement, activity, HRV, MET-level, and ECG for the Movisens Move4 and EcgMove4 devices
version: 0.9.2
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_context_package

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  movisens_flutter: ^0.1.5
  carp_mobile_sensing: ^0.9.2
  convert: ^2.1.1
  openmhealth_schemas: ^0.1.4

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_mobile_sensing:
#    path: ../carp_mobile_sensing/
  #movisens_flutter:
   # git:
   #   url: git://github.com/cph-cachet/flutter-plugins.git
   #   path: packages/movisens_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

