name: carp_health_package
description: CARP health sampling package. Samples health data from Apple Health or Google Fit.
version: 2.7.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_health_package

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.3.0
  carp_mobile_sensing: ^1.3.0

  health: ^8.0.0
  json_annotation: ^4.8.0
  uuid: '>=3.0.1 <5.0.0'
  permission_handler: ^11.0.0  

# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  lints: any
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
