name: carp_webservices
description: Flutter API for accessing the CARP web services - authentication, file management, data points, and app-specific collections of documents.
version: 0.3.2
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_webservices

environment:
  sdk: ">=2.3.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  carp_mobile_sensing: ^0.6.0
  http: ^0.12.0
  json_annotation: ^3.0.0
  retry: ^3.0.0

# Overriding carp libraries to use the local copy
# Remove this when done development
#dependency_overrides:
#  carp_mobile_sensing:
#    path: ../carp_mobile_sensing/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0
  test:

# The following section is specific to Flutter.
flutter:
