name: carp_core
description: The core domain model for the Copenhagen Research Platform (CARP) in Dart.
version: 1.7.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.2.0
  json_annotation: ^4.8.0
  iso_duration_parser: ^1.1.0
  meta: ^1.11.0

# Overriding carp core libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../carp_serializable/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any   
  flutter_lints: any


