name: carp_core
description: The core domain model for the CARP Mobile Sensing Framework in Flutter.
version: 0.40.2
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  carp_serializable: ^1.0.0
  meta: ^1.3.0
  uuid: ^3.0.4

# Overriding carp core libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_serializable:
  #   path: ../carp_serializable/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any   # For building json serialization
  json_serializable: any
  flutter_lints: any
  test: any
