name: carp_esense_package
description: The CARP eSense sampling package. Samples sensor and device events from the eSense ear plug device.
version: 0.12.2
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_esense_package
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #meta: ^1.1.8  
  json_annotation: ^3.0.1
  carp_mobile_sensing: ^0.12.1
  esense_flutter: ^0.3.0
  permission_handler: ^5.0.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
#dependency_overrides:
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/
#  esense_flutter:
#    path: ../../../../flutter-plugins/packages/esense_flutter/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.0.0
  test:

# The following section is specific to Flutter.
flutter:
