name: carp_study_generator
description: Utilities for generating CARP Mobile Sensing studies
version: 1.3.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.3.0
  carp_mobile_sensing: ^1.3.0
  carp_webservices: ^2.0.1
  carp_backend: ^1.3.1
  carp_apps_package: ^1.3.0
  carp_context_package: ^1.3.0
  carp_audio_package: ^1.3.0
  carp_esense_package: ^1.3.0
  carp_polar_package: ^1.3.0
  carp_survey_package: ^1.3.0
  carp_health_package: ^2.7.0
  # carp_communication_package: ^1.3.0
  carp_connectivity_package: ^1.3.0

  research_package: ^1.4.0
  cognition_package: ^1.5.0

  yaml: ^3.1.0
  meta: ^1.3.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../../carp_serializable/
#   carp_core:
#     path: ../../carp_core/
#   carp_mobile_sensing:
#     path: ../../carp_mobile_sensing/
#   carp_webservices:
#     path: ../../backends/carp_webservices/
#   carp_backend:
#     path: ../../backends/carp_backend/
#   carp_apps_package:
#     path: ../../packages/carp_apps_package/
#   carp_connectivity_package:
#     path: ../../packages/carp_connectivity_package/
#   carp_communication_package:
#     path: ../../packages/carp_communication_package/
#   carp_context_package:
#     path: ../../packages/carp_context_package/
#   carp_audio_package:
#     path: ../../packages/carp_audio_package/
#   carp_esense_package:
#     path: ../../packages/carp_esense_package/
#   carp_polar_package:
#     path: ../../packages/carp_polar_package/
#   carp_survey_package:
#     path: ../../packages/carp_survey_package/
#   carp_health_package:
#     path: ../../packages/carp_health_package/
#   research_package:
#     path: ../../../../research.package
#   cognition_package:
#     path: ../../../../cognition_package

# Overriding carp libraries to use github branch
#
# NOTE - you need to run "flutter pub upgrade" and "flutter pub get" in order to download the lastest
# versions from Github.
# dependency_overrides:
#   carp_core:
#     git:
#       url: https://github.com/cph-cachet/carp.sensing-flutter.git
#       ref: develop
#       path: carp_core
#   carp_mobile_sensing:
#     git:
#       url: https://github.com/cph-cachet/carp.sensing-flutter.git
#       ref: develop
#       path: carp_mobile_sensing
#   carp_context_package:
#     git:
#       url: https://github.com/cph-cachet/carp.sensing-flutter.git
#       ref: develop
#       path: packages/carp_context_package/
#   carp_survey_package:
#     git:
#       url: https://github.com/cph-cachet/carp.sensing-flutter.git
#       ref: develop
#       path: packages/carp_survey_package/
  # # carp_connectivity_package:
  # #   git:
  # #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  # #     ref: develop
  # #     path: packages/carp_connectivity_package/
  # carp_audio_package:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: packages/carp_audio_package/
  # carp_apps_package:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: packages/carp_apps_package/
  # carp_health_package:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: packages/carp_health_package/
  # carp_esense_package:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: packages/carp_esense_package/
  # carp_polar_package:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: packages/carp_polar_package/
  # carp_backend:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: backends/carp_backend/
  # carp_webservices:
  #   git:
  #     url: https://github.com/cph-cachet/carp.sensing-flutter.git
  #     ref: develop
  #     path: backends/carp_webservices/
  # research_package:
  #   git:
  #     url: https://github.com/cph-cachet/research.package.git
  #     ref: dev-carp-core-0_40_0
  # cognition_package:
  #   git:
  #     url: https://github.com/cph-cachet/cognition_package.git
  #     ref: develop


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
