name: carp_connectivity_package_example
description: Examples of how to use the CANS Connectivity Package.
version: 0.40.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_core:
  #   path: ../../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_connectivity_package:
    path: ../

dev_dependencies:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
