# For information on the generic Dart part of this file, see https://dart.dev/tools/pub/pubspec
name: carp_survey_package
description: CARP survey sampling package. Samples survey data from the Flutter Research Package.
version: 0.1.0
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_survey_package

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  carp_mobile_sensing: ^0.6.3
  openmhealth_schemas: ^0.1.4
  research_package: ^0.1.2

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
#  carp_mobile_sensing:
#    path: ../carp_mobile_sensing/
#  openmhealth_schemas:
#    path: ../../openmhealth_schemas/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^3.0.0
  test:

# The following section is specific to Flutter.
flutter:
