name: carp_connectivity_package
description: CARP connectivity sampling package. Samples connectivity status, bluetooth devices, and wifi access points.
version: 1.5.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_connectivity_package

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.4.0
  carp_mobile_sensing: ^1.4.0
 
  json_annotation: ^4.8.0
  permission_handler: ^11.0.0  
  connectivity_plus: ^6.0.0    # connectivity events
  network_info_plus: ^5.0.0    # wifi ssid name
  flutter_blue_plus: ^1.15.0   # bluetooth scan
  crypto: ^3.0.0               # hashing sensitive data
  
# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../../carp_serializable/
#   carp_core:
#     path: ../../carp_core/
#   carp_mobile_sensing:
#     path: ../../carp_mobile_sensing/

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
